# Buildspec Reference Doc: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

version: 0.2

phases:
  pre_build:
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - pip install pytest
      - echo "[+] Running tests..."
      - python -m pytest
  post_build:
    commands:
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/hello_world_flask:latest-codebuild .
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/hello_world_flask:latest-codebuild

cache:
  paths:
    - '/root/.cache/pip'