# Buildspec Reference Doc: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

version: 0.2

phases:
  install-dependencies:
    commands:
      - pip install -r requirements.txt
  test:
    commands:
      - pip install pytest
      - echo "[+] Running tests..."
      - python -m pytest tests/ -v

cache:
  paths:
    - '/root/.cache/pip'