version: 2.1

orbs:
  python: circleci/python@0.2.1
  aws-ecr: circleci/aws-ecr@6.8.2

jobs:
  test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python -m pytest --junitxml="test_results/result.xml"
          name: Test

  lint:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
            pip install flake8
            # stop the build if there are Python syntax errors or undefined names
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          name: lint

  build-and-publish:
    executor: python/default
    steps:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          setup-remote-docker: true
          create-repo: true
          dockerfile: Dockerfile
          path: ./
          profile-name: va-circleci
          region: AWS_REGION
          repo: hello_world_flask
          tag: 'circle-ci'

workflows:
  main:
    jobs:
      - test
      - lint
      - build-and-publish:
          requires:
            - test
            - lint
          context: va-circleci
